export const ErrorCode = {
  COMPANY_USERNAME_ALREADY_IN_USE: "COMPANY_USERNAME_ALREADY_IN_USE",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  COMPANY_NOT_FOUND: "COMPANY_NOT_FOUND",
  COMPANY_INVALID_STATUS_TRANSITION: "COMPANY_INVALID_STATUS_TRANSITION",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
