export const ErrorCode = {
  COMPANY_USERNAME_ALREADY_IN_USE: "COMPANY_USERNAME_ALREADY_IN_USE",
  COMPANY_NOT_FOUND: "COMPANY_NOT_FOUND",
  COMPANY_INVALID_STATUS_TRANSITION: "COMPANY_INVALID_STATUS_TRANSITION",
  COMPANY_USERNAME_CHANGE_NOT_ALLOWED: "COMPANY_USERNAME_CHANGE_NOT_ALLOWED",
  COMPANY_USERNAME_UNCHANGED: "COMPANY_USERNAME_UNCHANGED",
  COMPANY_USERNAME_CHANGE_RATE_LIMITED: "COMPANY_USERNAME_CHANGE_RATE_LIMITED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
